### ISSUE TITLE
Doctor Section

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#1]
### Description

For understanding of UI/UX check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)

Create a section separately for displaying doctors where there'll be categorised according to their Specialization like General Physician, Ear-Nose-Throat (ENT) Specialist, Gynecologist, Obstetrician, Laparoscopic Surgeon, General Surgeon, Proctologist, Hair Transplant Surgeon, Plastic Reconstruction Surgeon, Plastic Surgeon, Cosmetologist, Liver Transplant Surgeon, Hepato-Biliary-Pancreatic, Urologist . with some vector art image and random images .

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-15 (9)](https://user-images.githubusercontent.com/78967360/173747726-b4966c7a-7c0c-469b-9615-1f48af2a9c43.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by nitin094-hub** [comment]
Can I work on this?

**Comment by nitin094-hub** [comment]
I have to separately display names of doctors according to their specializations, right?

**Comment by ItsRoy69** [comment]
Yes.. like cards

**Comment by nitin094-hub** [comment]
I am planning to make something like this. When some user clicks on this box, it will show all the doctor's names with this particular specialization.
![Screenshot (112)](https://user-images.githubusercontent.com/73329655/173515131-3670f041-c012-4948-b3e8-3f0f6de7a211.png)
.

**Comment by nitin094-hub** [comment]
Where and what is on the doctorinfo page?

**Comment by ItsRoy69** [comment]
You should check the community guidelines and any extension can be used which will be running smoothly when we press "npm start".
