### ISSUE TITLE
Debug "OxygenSupplier.js"

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#105]
### Description

There is some bug in the "OxygenSupplier" page which creates an issue in deployment as you can see in "3fb0540a296f2b143c28c03e4ffb7f8bcf6aa6c0" commit . Try to debug

### Screenshots

![2022-09-05 (1)](https://user-images.githubusercontent.com/78967360/188361435-11969f24-d0f0-42f8-a0c4-4c7916e15e75.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Klaha** [comment]
@ItsRoy69 
I'd like to take a look at this bug if you allow me too 🙏🏻

**Comment by ItsRoy69** [comment]
Go for it
