### ISSUE TITLE
DonatePlasma Changes

### ISSUE THREAD

**Issue by Vansh-Baghel** [ItsRoy69/DocTalk#109]
### What would you like to share?

On issue #106, the changes I made were very much completed wrt UI. Its PR number was #107 which is still pending and I see another PR being merged for the same issue and issue has been closed.Also @ItsRoy69 assigned me for it. Whats the reason of not accepting #107 ?

**Comment by ItsRoy69** [comment]
There has been some bug in the page.. that'll be solved.. and your PR will be merged so that it gets deployed .
