### ISSUE TITLE
Add Doctor section in Services section in HomePage

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#11]
### Description

Add separate box for "doctors" under Services section in HomePage so that users can get infos about Doctors and get consultation.

In this section: Add another box

### Screenshots

![2022-06-12](https://user-images.githubusercontent.com/78967360/173210812-28ded2db-74d2-4a6d-8a26-50ce180e306b.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by alagumuthiah** [comment]
Hi, I have added the doctor section. Included two Pages under Pages folder Doctorinfo.jsx and Doctorcontact.jsx
Included the doctor section under service.

I have done only the client side for now, I would also like to include the server side #1 Doctor section as well.

And edited the image part by using Card-6 image for the Doctors Section. Let me know if there is any another card image for the doctor section.

Please find the screenshot below:

<img width="1440" alt="Screenshot 2022-06-13 at 5 38 44 PM" src="https://user-images.githubusercontent.com/57620699/173469769-6736c695-2b04-4ca9-8b25-5b21219e64d5.png">

I have raised a PR Fix:Add doctor section. 

#8
