### ISSUE TITLE
Debug the website 

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#112]
### Description

There is some bug in the page which creates an issue in deployment as you can see in "0348b0a9522881ccc4e458c1fdffc22a6150d63f" commit . Try to debug

### Screenshots

![2022-09-11](https://user-images.githubusercontent.com/78967360/189512056-e9533991-0fc2-4424-ba03-dd117e041efa.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by RoySounak** [comment]
Hello, according to this post it seems like two times import has been done in App.js. This will be my contribution if you allow me to do.

**Comment by RoySounak** [comment]
@ItsRoy69 after fixing this above issue, I have faced some CSS issues for which the web app is not rendering. 
![image](https://user-images.githubusercontent.com/60769490/189515536-b7711aa6-69ec-4507-9206-ec4c8b296bb1.png)

Will I fix those issues too?

**Comment by rohitroy-github** [comment]
Is the issue solved ?

**Comment by ItsRoy69** [comment]
Nope

**Comment by RoySounak** [comment]
@ItsRoy69 Can you tell why the vercel deployment got fail?

**Comment by Klaha** [comment]
@ItsRoy69 
I know this is not my issue, but I've fixed the vercel build error con this PR
https://github.com/ItsRoy69/DocTalk/pull/115

Also, be aware when merging latest changes; as 0348b0a9522881ccc4e458c1fdffc22a6150d63f introduced a plethora of weird characters that broke the build, and 20296bae05f9392b41edb6ac4b84a2d8207c15a3 introduced code duplicates.
