### ISSUE TITLE
Oxygen Supplier page is not rendering as expected. 

### ISSUE THREAD

**Issue by RoySounak** [ItsRoy69/DocTalk#116]
### Description

Issue in .css file. 

### Screenshots

![image](https://user-images.githubusercontent.com/60769490/189577414-801c0c6c-d831-4b01-8c2e-9ec2c72ad7b5.png)

![image](https://user-images.githubusercontent.com/60769490/189577519-02877fd6-acd6-4afb-8410-138834b5f8aa.png)

**Comment by RoySounak** [comment]
@ItsRoy69 May I fix this issue?

**Comment by ItsRoy69** [comment]
do it

**Comment by ask-1710** [comment]
@RoySounak are you still working on this issue? If not, I want to work on it.
