### ISSUE TITLE
[DOCS] copyrights or typo?

### ISSUE THREAD

**Issue by Tamir198** [ItsRoy69/DocTalk#117]
### Description

Hey, I have noticed that there is a `c` at the bottom of the README (first image), is this a mistake or support to be copyrighted (second image)?

If this is copyrights maybe change it to the copyrights symbol?

### Screenshots

![image](https://user-images.githubusercontent.com/34707669/190395614-20446545-fe8a-43ec-997c-0eb5f3f08666.png)
![image](https://user-images.githubusercontent.com/34707669/190395622-bba77672-2f22-4f1d-ae9b-e4ba9d843127.png)

**Comment by ItsRoy69** [comment]
Typo...there needed to write "Please give a star to support"
