### ISSUE TITLE
UI/UX in HomePage

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#12]
### Description

Make some changes in the homepage with some animations and minimise the contents of the website which is hurting to our eyes which will make it look more attractive. You can use any libraries to add animation and effects but it should be supported by ReactJS.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Roshani9731** [comment]
@ItsRoy69 Can I work on this?

**Comment by warmachine028** [comment]
I would like to work on this issue

**Comment by warmachine028** [comment]
### Current View
|home page| ambulances page |
|:-------:|:-----:|
| ![home](https://user-images.githubusercontent.com/75939390/185602528-78fc475d-c8b5-413e-82c7-d3c06d48106d.jpg)|![ambulance](https://user-images.githubusercontent.com/75939390/185602930-1b9cf894-83ca-4349-898d-4b352e6bddd9.jpg)|

### Should the container padding be preserved like above images ☝️ or it must be removed like the below images 👇?

### Proposed Updated View 
|home page| ambulances page |
|:-------:|:-----:|
| ![home-fixed](https://user-images.githubusercontent.com/75939390/185602538-eea7d092-8b6d-404c-9322-92e97f5ca411.jpg) | ![ambulance-fixed](https://user-images.githubusercontent.com/75939390/185603847-6c1bdf2a-11cb-4610-87ff-b62d2ba891bb.jpg) |

### Fixed distorted images in helping hand

![distorted images](https://user-images.githubusercontent.com/75939390/185604829-17916a85-44d3-4a7d-93b6-5dcde67a1ae3.jpg)

### Fixed Contact Section 
![contact](https://user-images.githubusercontent.com/75939390/185605049-4cd8cb0d-35b4-46a3-a68d-84380a294fe3.jpg)

### Additional Fixes
- Responsive fix for #84 
![fixes_responsive](https://user-images.githubusercontent.com/75939390/185605783-4a8b7a2a-0bb1-447e-a83d-68869b79ea94.jpg)

### Please let me know if any other changes are required and the proposed changes are acceptable or any further modifications required before making a PR.

**Comment by ItsRoy69** [comment]
The current view looks cleaner as it doesn't gets streched but try to keep helping hand section in even numbers in both lines orelse it'll be hurting the eyes. 
Tip : You can add hover effects on helping hand images like https://codesandbox.io/s/p997l6vl00 to make it more attractive

**Comment by warmachine028** [comment]
Sure! I will retain the Current View.
I have added this hover animation in the helping hand images. Will it be acceptable?
![hover](https://user-images.githubusercontent.com/75939390/185731840-a94ff664-1894-4c68-83a4-c846eff74c78.gif)

**Comment by ItsRoy69** [comment]
Looks good to me
