### ISSUE TITLE
Fix: Donors page

### ISSUE THREAD

**Issue by Mahir1015** [ItsRoy69/DocTalk#120]
### Description

1. Fix the design of donors page

### Screenshots

![Screenshot (12)](https://user-images.githubusercontent.com/66949598/191260338-2b671b5c-6761-4d5b-98e7-e02cb2dcb542.png)
![Screenshot (13)](https://user-images.githubusercontent.com/66949598/191260355-1925b717-36c7-42f4-86d1-489a70ab4451.png)

**Comment by satyamgupta1495** [comment]
Hey Mahir, I'd like to work on this issue!
