### ISSUE TITLE
Fix: Backend of Hospital Bed Supplier Registration

### ISSUE THREAD

**Issue by Mahir1015** [ItsRoy69/DocTalk#130]
### Description

Connect it to the server.

**Comment by ask-1710** [comment]
@ItsRoy69 I would like to work on this issue.

**Comment by Mahir1015** [comment]
@ask-1710 It's already been fixed. I'm about to make a PR.

**Comment by ask-1710** [comment]
@Mahir1015 Okay, thanks for the update!
