### ISSUE TITLE
[OTHER] Improve Homepage Maintainability

### ISSUE THREAD

**Issue by ShivangM** [ItsRoy69/DocTalk#153]
### What would you like to share?

The homepage component contains a repeating code of Services and Helper hand card. Separate components should be made for them for better maintainability and to reduce code reputation. Also, the contact form should be made as a separate component.

### Screenshots:

**1. Services:**

![image](https://user-images.githubusercontent.com/63797338/216528103-28e330ba-fa77-4049-b441-73710538b6cb.png)

**2. Helping Hand Cards:**

![image](https://user-images.githubusercontent.com/63797338/216528163-4273173e-fc13-4932-9143-9857d8dedd28.png)

This kind of repetition can be improved by creating a separate component.

### Additional information

Please assign me this task under the diversion 2023 tag.

**Comment by rt-001** [comment]
can I work on this issue?

**Comment by ShivangM** [comment]
> can I work on this issue?

Hi, I already made a PR regarding this one. I'm waiting for the verification.
