### ISSUE TITLE
Hover feature for the submit button on the donor page

### ISSUE THREAD

**Issue by prakhar-1005** [ItsRoy69/DocTalk#159]
### Description

The submit button on the donor page does not have hover feature like the other buttons on home page. I would like to add it.

### Screenshots

![Screenshot (129)_LI](https://user-images.githubusercontent.com/94559623/216992304-ed7fc229-14c3-497b-99f6-d8aa7af8d423.jpg)

**Comment by rt-001** [comment]
I would like to work on this

**Comment by rt-001** [comment]
I would like to work on this

**Comment by ItsRoy69** [comment]
@prakhar-1005 you wanna work on this issue ?
