### ISSUE TITLE
Backend Implementation for User Registration / Login

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#17]
### Description

Add backend for User Registration / Login in Database with
Create a section separately for registration of users where they can register themselves on this website .
It should have following points :

First name
Last name
Email
Password
Exact Location
Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

**Comment by ItsRoy69** [comment]
Go for it

**Comment by Mutesa-Cedric** [comment]
> 

what will a user have?

**Comment by ItsRoy69** [comment]
Create a section separately for registration of users where they can register themselves on this website .
It should have following points :

First name
Last name
Email
Password
Exact Location
Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP

**Comment by Mutesa-Cedric** [comment]
finishing in one hour!

**Comment by Mutesa-Cedric** [comment]
https://github.com/ItsRoy69/DocTalk/pull/25#issue-1271269187

completed!
