### ISSUE TITLE
User Login Frontend 📐

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#18]
### Description

Make the login page as responsive in MOBILE , TAB . DESKTOP , LAPTOP.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by meenaljain0303** [comment]
i would like to work on this issue
