### ISSUE TITLE
Create Navbar as the Figma design 

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#21]
### Description

For understanding of UI/UX check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-15 (8)](https://user-images.githubusercontent.com/78967360/173748020-496c0dae-b97d-4e09-9585-31be9d0738e2.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by nitin094-hub** [comment]
I would like to work on this

**Comment by nitin094-hub** [comment]
You want to replace the old navbar, right?

**Comment by ItsRoy69** [comment]
I want the navbar to be exact as I've done in the figma design. + The above image

**Comment by nitin094-hub** [comment]
But there is already a navbar!

**Comment by ItsRoy69** [comment]
Kindly follow the steps and contributing guidelines before workimg on the project

**Comment by ItsRoy69** [comment]
Yes

**Comment by MarkWasfy00** [comment]
can you assign it to me

**Comment by ItsRoy69** [comment]
You can work on other issues... Like banner, footer, etc.

I'll assign if @nitin094-hub fails to submit the task within Friday.

**Comment by MarkWasfy00** [comment]
i already worked on it and almost finished it

**Comment by ItsRoy69** [comment]
Sure

**Comment by ItsRoy69** [comment]
Till then you can work on other sections
