### ISSUE TITLE
Add "Helping Hand" section

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#24]
### Description

For understanding of UI/UX check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)

"Helping Hand"  section should be done in the Home.jsx file . You don't need to make another file to add this section.

Code should be clean and section should be divided with comments so that viewers can differentiate the code.

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-15 (1)](https://user-images.githubusercontent.com/78967360/173738043-33730645-8655-41ab-b3ec-7cff2bf5680a.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by deeola** [comment]
Hello, I would love to work on this

**Comment by deeola** [comment]
Hello Roy, I'm working on this right now and I have some questions I'll need to ask. Design-wise.

1) Is it possible to reduce the number of shadows we have on this design? It is a little bit too much, especially the ones around the icons' borders. The card shadow makes sense but I feel the blue box shadow makes it look not so good. That's your call.


2) Can we have a change of icons to probably free minimalist icons on font awesome? I can see some of the icons are still watermarked and that's not good. You can't ship a product with that. 

3) Out of my current task, I noticed some of the design files on Figma are not following some basic rules of design especially alignment( You can check the contact page for that). 

4) Generally, I would love to make some changes to the designs (I have some experience doing UI/UX).

Please, let me know you thoughts about these points

**Comment by ItsRoy69** [comment]
For sure. Do changes in UI/UX and being a developer myself I feel like experimenting stuffs is important. I made the design just because there are many other developers who dont know what to do. They are confused. So, it'll be better if you make some changes and make a pull request.

At the end of the day, opensource is not just about PR ... Its more than that. So do whatever you feel like .. just remember to follow the same theme.
That's it

**Comment by ItsRoy69** [comment]
Sure

**Comment by nitin094-hub** [comment]
Is anyone working on this?

**Comment by ItsRoy69** [comment]
Deeola had previously asked to assign him but its been 4 days....so if you wanna work in this iaaue thn i can assign you

**Comment by nitin094-hub** [comment]
Please assign this to me.
