### ISSUE TITLE
Add contact section in HomePage

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#27]
### Description

For understanding of UI/UX check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-15](https://user-images.githubusercontent.com/78967360/173737881-132d0660-79c5-42c6-abc7-f17d95b2e873.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by deeola** [comment]
Hello Roy, is this up for grabs?

**Comment by prabhpreet-code** [comment]
I would love to work on this...

**Comment by ItsRoy69** [comment]
> Hello Roy, is this up for grabs?

Didn't understood...please elaborate

**Comment by deeola** [comment]
I can see you've assigned it already, can I work on others?

**Comment by ItsRoy69** [comment]
Yes you can work on other sections..

**Comment by prabhpreet-code** [comment]
@ItsRoy69 do I need to structure validation and error handling part as well or just simple frontend component will work fine? 

One thing more that the box shadow that is mentioned on figma is to be put on hover or simply under the input element without hover?

**Comment by ItsRoy69** [comment]
Nope just the frontend...

Box shadow is just the input without hover.. you can add hover on button

**Comment by prabhpreet-code** [comment]
Hello @ItsRoy69... I have done making it for desktop and one thing I would like to ask is that for making it responsive should I inculcate media queries or should simply work fine with width as percentages.
Also am enclosing the ss for the desktop version and pls suggest if some changes are needed.
![Screenshot (2145)](https://user-images.githubusercontent.com/66708921/174020518-730a26b7-5be9-45db-bc41-dedcc7f0ff8f.png)
![Screenshot (2146)](https://user-images.githubusercontent.com/66708921/174020579-064aff61-02ca-4c22-b8dd-6b1081b56b59.png)

**Comment by ItsRoy69** [comment]
Use media queries and this looks great .

**Comment by prabhpreet-code** [comment]
The second screenshot is for hovering over the button element and just trying something different so u can suggest whether to keep it or not.

**Comment by prabhpreet-code** [comment]
> 
Cool thanks!

**Comment by prabhpreet-code** [comment]
Can you look if there are some changes needed to be made...?
![Screenshot (2147)](https://user-images.githubusercontent.com/66708921/174085962-536c81e0-c242-490f-aa9d-7d46429314bf.png)
![Screenshot (2148)](https://user-images.githubusercontent.com/66708921/174085980-fbcb4ce5-e72d-4ae2-8667-a96c8b59f841.png)
![Screenshot (2149)](https://user-images.githubusercontent.com/66708921/174086000-ac8f07dd-2d3c-408e-ba35-a4583962c865.png)
![Screenshot (2150)](https://user-images.githubusercontent.com/66708921/174086007-b73dfe35-feab-4330-b013-29ed84babae4.png)
![Screenshot (2151)](https://user-images.githubuserc
![Screenshot (2152)](https://user-images.githubusercontent.com/66708921/174086023-812cf1f0-2c11-4396-9c2f-952e7537f1c8.png)
ontent.com/66708921/174086012-b2fa675c-e990-4cfb-acfa-c021ede031e1.png)


![Screenshot (2153)](https://user-images.githubusercontent.com/66708921/174086037-b5c5a5af-8b02-4bf7-8c90-e01974914635.png)

**Comment by ItsRoy69** [comment]
Looks good

**Comment by ItsRoy69** [comment]
Push the code from your local storage to the forked repository and make a pull request in this repo.

**Comment by prabhpreet-code** [comment]
While I was making a pull request, in description box it was written that I have worked under which open source event.. so can you please tell me that what should I write here as currently m not aware about any of the events or should I left it as blank?

**Comment by ItsRoy69** [comment]
leave it blank..because you've not registered under any opensource events now
