### ISSUE TITLE
Login Page for Doctors

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#3]
### Description

Create a section separately for login of doctors where they can register themselves on this website .
It should have following points :
 - Email
 - Password
 
Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by fduschka** [comment]
Isn't this the same as #2?

**Comment by ItsRoy69** [comment]
Nope. In registration doctors have to register themselves under this website whereas under login page they won't have to register for the nect time. They'll only have to login using password and email ID .

**Comment by fduschka** [comment]
This is included within PR #10 under the route /doctor/login
<img width="968" alt="Bildschirmfoto 2022-06-11 um 21 03 02" src="https://user-images.githubusercontent.com/63229744/173219427-dae33f0b-f53c-4362-bbb3-6e45391113e9.png">
