### ISSUE TITLE
Add hover feature in buttons of Services Section

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#33]
### Description

Add hover feature in buttons of Services Section with a bit of realistic css in it

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by MarkWasfy00** [comment]
can i restore the old photo that i made in heading cause the new one have some problems + fixing the contact us section and unit all the hover state in all buttons

**Comment by ItsRoy69** [comment]
1. The old photo took a lot more space and alignment was broken because it was just extracted directly from the figma file alongwith the shadow effects.. instead of adjusting the shadow manually. So if you can work on that.. then go for it.
2. You can put hover state on the buttons. 
3. You can improve the design in the contact section with your own UI/UX. 
4.
