### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#4]
### Description

Create a section separately for registration of users where they can register themselves on this website .
It should have following points :
 - First name
 - Last name
 - Email
 - Password
 - Exact Location
 
Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by nitin094-hub** [comment]
Can I take up this issue?

**Comment by nitin094-hub** [comment]
UI should be the same as the doctor register?

**Comment by ItsRoy69** [comment]
UI should be same as the doctor but if you want you can add illustrations so that the UI looks cool.

**Comment by nitin094-hub** [comment]
what are illustrations?

**Comment by ItsRoy69** [comment]
![2022-06-13](https://user-images.githubusercontent.com/78967360/173278354-461379a7-6d72-458f-a8d2-8b1e9d47876a.png)
