### ISSUE TITLE
Patients Registration

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#43]
### Description

Create a page separately for registration of patients where there'll be categorised according to their diseases. 

For referennce check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-21](https://user-images.githubusercontent.com/78967360/174708897-8c27c426-057f-4430-a9dd-814e7d2ef511.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by nitin094-hub** [comment]
Can you assign this to me?

**Comment by nitin094-hub** [comment]
Is this registration only for plasma donors or there are any other categorizations?

**Comment by ItsRoy69** [comment]
Patients registration is only for doctor section.
This is just an example given to show on how patient registration form should look like.

Plasma donor is given as an example.

**Comment by nitin094-hub** [comment]
So I only have to make this form, right?
