### ISSUE TITLE
Registration of donors

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#45]
### Description

Create a page separately for registration of donors with id which will change according to their requirements like Ambulance service, Medicine Supply, Oxygen Supply, Plasma Donate, Hospitals Beds

For reference check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

This is an example of how you'll build the page:

### Screenshots

![2022-06-21](https://user-images.githubusercontent.com/78967360/174708897-8c27c426-057f-4430-a9dd-814e7d2ef511.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by nitin094-hub** [comment]
Isn't this the same as patient registration?

**Comment by ItsRoy69** [comment]
Yeah.. just the text and features will be different

**Comment by nitin094-hub** [comment]
Then why need this separate issue?

**Comment by nitin094-hub** [comment]
So what changes do I have to make on the patient's registration?
