### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#5]
### Description
For understanding of UI/UX check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)
Create a separate footer section  in this website eventhough there is a "contact" section named as "footer" .
Do the necessary changes by renaming files and debug.

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-15 (7)](https://user-images.githubusercontent.com/78967360/173746762-9b09b273-c3e2-4f3d-8bd6-ac2fd768703d.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by MarkWasfy00** [comment]
There's a component that called footer which is the ('contact')

**Comment by ItsRoy69** [comment]
Make changes in the folder by adding many more features in the footer section like social media links, copyright, logo, one-liner details of the website.

**Comment by nitin094-hub** [comment]
Is someone working on this?

**Comment by ItsRoy69** [comment]
Nope

**Comment by nitin094-hub** [comment]
Can you assign this to me?
