### ISSUE TITLE
Plasma Donor Registration

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#51]
### Description

Create a page separately for registration of plasma donors in "DonatePlasma.js" file with features given in the screenshot. 

For reference check [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1)

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-25](https://user-images.githubusercontent.com/78967360/175762136-1da08570-4c27-4e55-9a26-ea11cb227d65.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Sarrene9** [comment]
Hi I would like to work on this

**Comment by Sarrene9** [comment]
The last time I completed the About and Contact task but got unassigned before Friday.

**Comment by ItsRoy69** [comment]
Try to complete this before friday

**Comment by Sarrene9** [comment]
Alright, noted on that

**Comment by nitin094-hub** [comment]
Is anyone working on this?

**Comment by Sarrene9** [comment]
Will commit today ya

**Comment by Sarrene9** [comment]
Done. Committed to the fork.

**Comment by ItsRoy69** [comment]
Make a PR
