### ISSUE TITLE
Plasma Donor Page

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#59]
### Description

Make the "plasmadonor" page which will show the list of plasma donors who has registered under this website... with some animations to look it more attractive. You can use any libraries to add animation and effects but it should be supported by ReactJS.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Furkangunduz** [comment]
Hello,
I am working on this by this figma file [here](https://www.figma.com/file/6qxdJMmXpIlXS3sWEAvVt8/Untitled?node-id=0%3A1).

**Comment by audrey2001** [comment]
Hi,I would love to work on this if it's still open 😊

**Comment by audrey2001** [comment]
hi, done with it and i sent a PR already
