### ISSUE TITLE
Responsiveness of Homepage

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#6]
### Description

Make the homepage as responsive in MOBILE , TAB . DESKTOP , LAPTOP.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Roshani9731** [comment]
@ItsRoy69 Can I work on this issue?

**Comment by ItsRoy69** [comment]
Sure

**Comment by Mahir1015** [comment]
@ItsRoy69  can you assign it to me?

**Comment by Mahir1015** [comment]
#7 @ItsRoy69  The responsiveness of desktop and laptop is fine. So do I just make the homapge responsive in mobile &  tab?

**Comment by ItsRoy69** [comment]
Yep.. you need to fix the responsiveness on mobile and tab

**Comment by Mahir1015** [comment]
#8 @ItsRoy69 Before making any changes
![Screenshot (38)](https://user-images.githubusercontent.com/66949598/184189731-90b5cfbe-eed8-471b-8de3-bc0a8758c2c8.png)
![Screenshot (36)](https://user-images.githubusercontent.com/66949598/184189723-c29b6f80-9a39-4d9f-a1ea-97581d855f83.png)
![Screenshot (37)](https://user-images.githubusercontent.com/66949598/184189727-4b954d0a-edee-4e40-8f7a-70cceb8664b6.png)
![Screenshot (32)](https://user-images.githubusercontent.com/66949598/184189695-26d73879-849b-49e8-b42f-8618f4c4fb00.png)
![Screenshot (33)](https://user-images.githubusercontent.com/66949598/184189706-9239703a-1ed1-4e7e-8ea3-626b2afe1e9b.png)
![Screenshot (34)](https://user-images.githubusercontent.com/66949598/184189709-b27168c4-bb63-4335-88e2-215ac55d5ea9.png)
![Screenshot (35)](https://user-images.githubusercontent.com/66949598/184189715-03d3f4e7-31c2-46ad-a3fb-79f74687568f.png)
After making changes,
![Screenshot (40)](https://user-images.githubusercontent.com/66949598/184189908-378ffac2-07aa-4067-a438-fb192e7e5bcb.png)
![Screenshot (41)](https://user-images.githubusercontent.com/66949598/184189921-b4bf1e7f-b027-4ff9-881a-accd44c47d28.png)
![Screenshot (42)](https://user-images.githubusercontent.com/66949598/184189924-5a36dc83-bda6-4565-affd-2afdf257688c.png)
![Screenshot (43)](https://user-images.githubusercontent.com/66949598/184189925-69ac9f3d-f124-4d7c-99b4-9c346053297d.png)
![Screenshot (44)](https://user-images.githubusercontent.com/66949598/184189930-25cf03d3-21ff-4790-9392-8a13519a7f3a.png)

**Comment by ItsRoy69** [comment]
Well done
