### ISSUE TITLE
Hospital Beds Page

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#60]
### Description

Make the "hospitalbed" page which will show the list of hospital bed that has been registered under this website... with some animations to look it more attractive. You can use any libraries to add animation and effects but it should be supported by ReactJS.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by aigerimmmm** [comment]
Hey @ItsRoy69 can I work on this issue?

**Comment by aigerimmmm** [comment]
Hey @ItsRoy69 what do you think about when you hover over bed image you can see the title? or is it better to do similar to Doctors page (showing one column list of available doctors)
![Screenshot1](https://user-images.githubusercontent.com/46799842/185695000-a0b4dbc2-6255-48f2-bf70-76e59892240f.png)

**Comment by ItsRoy69** [comment]
This looks cool ngl... Try to deploy on the cloned repo..
