### ISSUE TITLE
Ambulances Page

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#62]
### Description

Make the "ambulances" page which will show the list of  ambulances that has been registered under this website... with some animations to look it more attractive. You can use any libraries to add animation and effects but it should be supported by ReactJS.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Suman373** [comment]
From where are we getting the info? Is there any api endpoint?

**Comment by ItsRoy69** [comment]
api folder will be created later.. after the setup of backend.. right now just the hardcode will be fine

**Comment by Suman373** [comment]
Okk

**Comment by warmachine028** [comment]
I would like to work on this issue

**Comment by warmachine028** [comment]
## Can you please review the page which I made and suggest changes, before I create a PR.

1. Desktop View:

![laptop](https://user-images.githubusercontent.com/75939390/185070211-569250f8-7a05-4bf5-a9eb-8858adeb9314.png)

2. Also made the page responsive for all types of devices:

![mobile](https://user-images.githubusercontent.com/75939390/185070355-ae0f2f69-60fb-46d8-999e-fa7df262bc94.png)

![mobile2](https://user-images.githubusercontent.com/75939390/185070701-04bec115-2bbc-4bee-a64b-ad471ecb13d3.png)

### Additional Information:

- Added search by location functionality using react-autosuggest.

![react-select](https://user-images.githubusercontent.com/75939390/185071965-358abb32-e30b-4bb1-8860-9ffa559d34ba.jpg)

- Added 2 second loading functionality to mimic database fetching time.

![Screenshot 2022-08-17 135851](https://user-images.githubusercontent.com/75939390/185072356-4dd098c9-ecb0-4d49-9664-3e1c02b7fa78.jpg)

**Comment by ItsRoy69** [comment]
Looks good to me.. but ambulance picture needs to be changed as there is no input box in the form so there'll be only on picture that'll be generated in every box

**Comment by warmachine028** [comment]
Sure! I'll be making the change
