### ISSUE TITLE
Medicines Page

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#63]
### Description

Make the "medicines" page which will show the list of medicines that has been registered under this website... with some animations to look it more attractive. You can use any libraries to add animation and effects but it should be supported by ReactJS.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by IamGuneet** [comment]
Hi,
I d like to work on this issue, could you assign me to it?
@ItsRoy69

**Comment by IamGuneet** [comment]
@ItsRoy69 
I am new to open source, do guide me.

**Comment by ItsRoy69** [comment]
Firstly go through the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md), [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md) , then star and fork this repo. Clone it to your local repository and make the necessary changes

**Comment by Mahir1015** [comment]
@Vansh-Baghel you can work on this

**Comment by warmachine028** [comment]
If this issue is open, I would like to work on it

**Comment by lazyfuhrer** [comment]
hey is it still open ? if yes you can assign me

**Comment by ItsRoy69** [comment]
Go with it

**Comment by lazyfuhrer** [comment]
where can i find the list of medicines ? @ItsRoy69

**Comment by lazyfuhrer** [comment]
btw why are you declaring navbar and footer for each pages ? you could simply declare them once in app.js through routing. @ItsRoy69

**Comment by ItsRoy69** [comment]
I am thinking of revamping the site so it'll be great if you join https://diversion.tech/'s discord

**Comment by lazyfuhrer** [comment]
joined

**Comment by Vansh-Baghel** [comment]
@ItsRoy69 @MahirMahdi sorry for late reply, may I work on it? I can build it within a day or 2 as I've experience of doing so.

**Comment by Vansh-Baghel** [comment]
@ItsRoy69 @MahirMahdi where are the lists of medicines provided?

**Comment by MahirMahdi** [comment]
Here you go😀

![Screenshot 2023-02-05 163145](https://user-images.githubusercontent.com/66949598/216813970-eeedbfc0-22df-4ace-8a29-59564bdcec36.png)

**Comment by Vansh-Baghel** [comment]
> @Vansh-Baghel Here you go😀
> 
> ![Screenshot 2023-02-05 163145](https://user-images.githubusercontent.com/66949598/216813970-eeedbfc0-22df-4ace-8a29-59564bdcec36.png)

Sorry for late reply, starting to work on it!! 👌

**Comment by Vansh-Baghel** [comment]
@MahirMahdi @ItsRoy69  So I connected the backend but see no medicines posted. Also in the Schema of Med, there are only person's details and not medicine details. We would also have to post the medicineName when someone wants to donate or supply medicine.
May I get some social or community link for further contact? I can fix this issue, but will need active cooperation

**Comment by Vansh-Baghel** [comment]
added this property in the Schema, also every other property is false in required, which is redundant as required is by default false.
![ss2](https://user-images.githubusercontent.com/103327712/216820713-8adbc3d6-4485-421b-87b3-f66938a6a6bf.png)
