### ISSUE TITLE
"About Us" section inside "Home.js"

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#66]
### Description

Make the "About Us" section inside "Home.js" page which will tell about this website... with some animations to look it more attractive. You can use any libraries to add animation and effects but it should be supported by ReactJS.

You can check the screenshot for getting an idea

### Screenshots

![2022-07-25 (23)](https://user-images.githubusercontent.com/78967360/180778989-c47e1d2a-d816-462d-b319-bb61622b38bb.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by rohitroy-github** [comment]
The text you have used in the screenshot, that very text will be used in the Avout Us section right ?

**Comment by rohitroy-github** [comment]
Check this out > 

![image](https://user-images.githubusercontent.com/68563695/181707539-2a99b8b6-d7da-49f5-a0f8-f2ea37b001df.png)

![image](https://user-images.githubusercontent.com/68563695/181707711-7d260f14-a321-4fe6-ad91-17f80d69b9eb.png)


I have made a PR for this.
