### ISSUE TITLE
Linking of Navbar

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#67]
### Description

Link the "Navbar" section inside "Navbar.js" page to those different sections in this website... You can use any libraries but it should be supported by ReactJS.

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Rajarshi38** [comment]
Can you please elaborate more?

**Comment by ItsRoy69** [comment]
If you look closely to the website you'll see the navbar links are not working so .. you'll have to use <Link> and link navbar with different sections of the website

**Comment by Rajarshi38** [comment]
Oh ok! I can do this. Can you assign it to me?

**Comment by Rajarshi38** [comment]
I cannot see the itsroy69-doctalk branch, i can only see the main branch. 
![image](https://user-images.githubusercontent.com/72081132/181436979-a445e483-9a56-44b3-a780-9187fb95eb49.png)
