### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by paradigm-lab** [ItsRoy69/DocTalk#71]
### What would you like to share?

Containerizing the application using (Docker).

### Additional information

But before that we should need to identify which architecture does the application use. But it doesn't matter match

**Comment by ItsRoy69** [comment]
Go with it

**Comment by paradigm-lab** [comment]
We can just start as simple as possible. So is it a BFF Architecture

**Comment by paradigm-lab** [comment]
Sorry for been late to submit i am having a problem with my computer. Yesterday before my computer break i was starting the application for the front-end it started fine but having problem with starting the back-end

**Comment by ItsRoy69** [comment]
Backend is not yet complete
