### ISSUE TITLE
Backend of the patients signup & signin page

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#73]
### Description

Set the Backend of the signup & signin page and connect with frontend

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by Mahir1015** [comment]
@ItsRoy69 How about providing three options doctor, patient, and donor on the Signup page? There will be three different schemas for the following options inside the user's schema.

**Comment by ItsRoy69** [comment]
Yes you can do these changes.. and it'll be great tbh.. thanks for giving the suggestion

**Comment by Mahir1015** [comment]
Anytime. Assign it to me.

**Comment by Mahir1015** [comment]
@ItsRoy69 The schema for the three options will be the same just one or two additional field will be added to each option. Like for doctor a field of degrees will be added and another field for the type of doctor they are. How about that?

**Comment by ItsRoy69** [comment]
Yeah then in frontend some sections will also be added...sounds good to me

**Comment by Mahir1015** [comment]
@ItsRoy69  Sorry, I was a bit busy so I couldn't work on it. But I have already started. There is no donor schema. Will it be alright if I add all the fields of the user schema to the donor schema and a few additional fields like blood type and a boolean field about the type of donor they are?

**Comment by ItsRoy69** [comment]
Go with it

**Comment by Mahir1015** [comment]
Alright I'm removing the donate page and adding the same route to the donor option having the same fields.

**Comment by Mahir1015** [comment]
@ItsRoy69 In which directory did you save env file?

**Comment by ItsRoy69** [comment]
.env file is protected so it can't be shared like that.. so use use own .env credentials in server folder while running and also if you wanna help others then you can create a ".envexample" file and write all those env credentials halfway... So that password doesn't gets leaked as well as others can get way which credentials to put.... other contributors can get it and work on it.

**Comment by Mahir1015** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/66949598/187060419-1838f3e9-f491-44a6-83ef-da5f0c4ff63a.png)
![Screenshot (49)](https://user-images.githubusercontent.com/66949598/187060422-bc1b70be-fa6e-4f50-b4a1-6146e697ed11.png)
![Screenshot (50)](https://user-images.githubusercontent.com/66949598/187060424-4b260aa7-e188-410a-a01c-3a7377869871.png)
I've completed backend of the signup of all three options in the same way. I haven't worked on the frontend part but I'm raising an issue for that. You assign it to me after I raise it. As soon as you give me the green light, Im gonna make a PR.

**Comment by Mahir1015** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/66949598/187063197-8fa3a0e1-6a48-4f7e-986b-023e22bfb7f8.png)
![Screenshot (52)](https://user-images.githubusercontent.com/66949598/187063201-0060abc5-511d-48d3-8e4c-5267fb2dba7b.png)
![Screenshot (53)](https://user-images.githubusercontent.com/66949598/187063204-d52756a3-84c9-466a-947d-61510c7dc5cf.png)
I've fixed the backend of all three signup options and added an "envexample" file to help contributors connect to the database.

**Comment by Mahir1015** [comment]
@ItsRoy69

**Comment by ItsRoy69** [comment]
Looks good to me.. make a PR ..

**Comment by Mahir1015** [comment]
@ItsRoy69 close it.
