### ISSUE TITLE
Enhance the UX of the website more beautifully

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#83]
### Description

Enhance the UX of the website more beautifully

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/DocTalk/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/DocTalk/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-doctalk branch. Don't make pull request directly on main branch. After review maintainer will merge it.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #doctalk so that we can discuss the issue there together.

Cheers 🥂

**Comment by naman-ng** [comment]
Hi Roy, do you have some specific enhancements in mind.

**Comment by ItsRoy69** [comment]
There are many stuffs than can be implemented to improve the UIUX of the website which can be improved

1. The website and footer ssection looks odd
2. About Us section looks oddly big and hurts the user's eyes
3. In hospital bed page we see hospital beds are shown which a user can find to be difficult
4. The homepage can be made attractive by using different designs and colours too

**Comment by tanitoluwam** [comment]
Hi, could you assign me to this please, i would love to work on it

**Comment by Tapo41** [comment]
I'm currently exploring UI/UX and I'm really passionate about it, I would like to give it try to improve the interface of the web app

**Comment by ItsRoy69** [comment]
Go with it

**Comment by AJ-KUSHWAH** [comment]
Could you please consider assigning issue #83 to me? I'm eager to contribute and believe I can provide valuable insights and solutions to move the project forward.
