### ISSUE TITLE
Landing Page - Mobile responsiveness

### ISSUE THREAD

**Issue by IAmTamal** [ItsRoy69/DocTalk#84]
### Landing Page

 The **landing page** needs a little bit more love in mobile responsiveness (take a look at image 1)
 - The header `Doctalk` is hidden almost
 - The button might have been in center
 - Some images are broken as well !

## Image 1

![image](https://user-images.githubusercontent.com/72851613/185552351-9df7aa27-9c48-4509-ae90-6e99cc33fafd.png)

**Comment by warmachine028** [comment]
Working on it in #12

**Comment by IAmTamal** [comment]
> Working on it in #12

Awesome 🚀
