### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/DocTalk#88]
### Description

Someone can suggest a design to improve the UI/UX.
There are many stuffs than can be implemented to improve the UIUX of the website which can be improved

1. The website and footer section looks odd
2. About Us section looks oddly big and hurts the user's eyes
3. In hospital bed page we see hospital beds are shown which a user can find to be difficult
4. The homepage can be made attractive by using different designs and colours too

**Comment by bandya2003** [comment]
I'm currently exploring UI/UX in Canva and Figma , I would like to give it try to improve the interface of the web app

**Comment by Tapo41** [comment]
I'm currently exploring UI/UX , I'm passionate about it, I would like to give it try to improve the interface of the web app

**Comment by ItsRoy69** [comment]
Go with it

**Comment by Dwayne-B** [comment]
I'd like to contribute to this project can this assigned to me.
