### ISSUE TITLE
Improve UI/UX of signup pages

### ISSUE THREAD

**Issue by Mahir1015** [ItsRoy69/DocTalk#92]
### Description

UI/UX of all the signup pages needs to be improved.
1. Change the fonts.
2. The aspect ratio of the input fields needs to be better.
3. The icons look unappealing.

**Comment by Mahir1015** [comment]
@ItsRoy69 I worked on the signup pages but there were no signin/login pages  I couldn't work on them. So I'm raising issues for the signin/login pages. Assign them to me. I'll work on those.

**Comment by Mahir1015** [comment]
![Screenshot (58)](https://user-images.githubusercontent.com/66949598/188260220-bdd40d23-1d51-4159-9b96-685cfe4b6d1c.png)
![Screenshot (59)](https://user-images.githubusercontent.com/66949598/188260223-e2930321-fd9b-4730-85da-b296c345bdd7.png)
![Screenshot (60)](https://user-images.githubusercontent.com/66949598/188260224-9b2ab1bd-4e31-4b71-a0f8-6379d98ddaf8.png)
![Screenshot (61)](https://user-images.githubusercontent.com/66949598/188260226-e7ca8e79-d9b8-477c-afa2-bf1e62db68d2.png)
@ItsRoy69 here you go. These are the signup and signin pages. I'll make a PR after you review it.

**Comment by Mahir1015** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/66949598/188260309-81ab45d8-0c75-4130-a503-a2e3a95c48aa.png)
![Screenshot (63)](https://user-images.githubusercontent.com/66949598/188260313-ffc0040a-7cb1-4efa-b5cc-dd2b464ab96a.png)
![Screenshot (64)](https://user-images.githubusercontent.com/66949598/188260314-ac79167d-c109-4d1d-9cdd-10ef379c49c2.png)
![Screenshot (65)](https://user-images.githubusercontent.com/66949598/188260315-ed60227f-23bd-4fc3-a255-74db6dfc0c2a.png)
@ItsRoy69 here you go. These are the signup and signin pages. I'll make a PR after you review it.

**Comment by Mahir1015** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/66949598/188260376-04beb368-b228-4dee-a8c2-4086932b679c.png)
![Screenshot (67)](https://user-images.githubusercontent.com/66949598/188260378-4de4e9de-93c6-4a7c-932f-4f6f07986a2c.png)
![Screenshot (68)](https://user-images.githubusercontent.com/66949598/188260379-7df8b233-b85e-4b66-85b1-a2e0b33b03a2.png)
![Screenshot (69)](https://user-images.githubusercontent.com/66949598/188260380-3bc20c8e-a799-44de-9b50-7c5fa28bf2b9.png)
@ItsRoy69 here you go. These are the signup and signin pages. I'll make a PR after you review it.

**Comment by ItsRoy69** [comment]
Use some vectors to make it look better

**Comment by Mahir1015** [comment]
@ItsRoy69 to the input fields?

**Comment by Mahir1015** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/66949598/189154081-95cd6e3f-115b-48b2-8e66-ccf060d1332e.png)
![Screenshot (72)](https://user-images.githubusercontent.com/66949598/189154097-20042c2e-81ec-45ed-a3f8-250b1dcf9a42.png)
![Screenshot (73)](https://user-images.githubusercontent.com/66949598/189154102-cd95288f-fd27-4f94-a90d-cfd1cbeafeb8.png)
![Screenshot (74)](https://user-images.githubusercontent.com/66949598/189154112-d06fe2d5-554d-4a5b-aded-d5599f9bafe9.png)
@ItsRoy69 is it okay now?

**Comment by Mahir1015** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/66949598/189154372-4a429e2d-de0e-445d-8c71-36bff2397756.png)
![Screenshot (73)](https://user-images.githubusercontent.com/66949598/189154385-3c9c16d4-ee61-42dd-9aed-240745ff0828.png)
![Screenshot (74)](https://user-images.githubusercontent.com/66949598/189154392-7094d090-55aa-4c09-834a-82c46a3296b0.png)
![Screenshot (75)](https://user-images.githubusercontent.com/66949598/189154394-534d3595-de5a-42b7-bffc-fdbe6c9e2464.png)
@ItsRoy69 is it okay now?

**Comment by Mahir1015** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/66949598/189154713-14bb9c95-ed84-41ed-ae19-e306de9df0a7.png)
![Screenshot (73)](https://user-images.githubusercontent.com/66949598/189154728-32d87620-0d09-453a-9299-fd5ba345fa05.png)
![Screenshot (74)](https://user-images.githubusercontent.com/66949598/189154734-275735e2-eb91-49b1-8553-4e8931ae02d2.png)
@ItsRoy69 is it okay now?
