### ISSUE TITLE
Fix: Both backend and frontend of donor's signin/login page

### ISSUE THREAD

**Issue by Mahir1015** [ItsRoy69/DocTalk#97]
### Description

1. Create a sign-in/login page for donors.
2. Add it to the existing route.

**Comment by Vansh-Baghel** [comment]
If I create only front-end will it do?

**Comment by Vansh-Baghel** [comment]
If I only create the front-end , will it do?

**Comment by ItsRoy69** [comment]
Every contribution countd

**Comment by Mahir1015** [comment]
Sorry what? I didn't get it

**Comment by Vansh-Baghel** [comment]
1. So what **input fields** do uall need in all the 3 registration pages? Like name , age, etc etc.
2. Do ya'll want all the three on separate pages or want it in a single page as a dropdown? so that people can select registration type from the same page.

**Comment by Mahir1015** [comment]
@Vansh-Baghel it's already been fixed. I'll close this issue as soon as I make the PR. If you want to work on front end wait let me tag you on another issue.

**Comment by Vansh-Baghel** [comment]
Oh ok! How can I know that an issue has been fixed or not? Like I am new at contributing so need to understand

**Comment by Mahir1015** [comment]
Well usually the issue is closed as soon as it's resolved but in cases like this you can only know when you ask for assigning the issue to you.
